### ISSUE TITLE
[Feature Request] Support Steam overlay/achievements by allowing renaming of Stardew Valley.exe

### ISSUE THREAD

**Issue by BlueRaja** [ClxS/SMAPI#10]
The Skyrim extended API "supports" running the game through Steam still (including achievements and whatnot) by allowing you to rename the API launcher to "Skyrim.exe" and renaming the actual Skyrim.exe to something else.

SMAPI should be able to do something similar, maybe by taking the exe name as a command-line parameter?

**Comment by BlueRaja** [comment]
Hmm, I just found out that setting the launch parameters to
```"D:\Games\Steam\steamapps\common\Stardew Valley\StardewModdingAPI.exe" %command%```
Also works.

**Comment by BlueRaja** [comment]
It is apparently possible to trick Steam into thinking your mod launcher is the game when it is launched.  I'm not sure how to do that, but https://github.com/aEnigmatic/xcom2-launcher does it for XCOM using, I believe, SteamWorks.Net

**Comment by Entoarox** [comment]
I do believe that is what the steam_appid.txt file is there for.

**Comment by Pathoschild** [comment]
Thanks for the idea. Starting with SMAPI 1.0, we'll probably have an install script (#155) that enables Steam support without further user action. That will work by replacing the `StardewValley.exe` itself (with a backup), as you suggested in the first comment.

**Comment by Entoarox** [comment]
@Pathoschild Please do not change the major version number for SMAPI from 0, the FarmHand SMAPI compatibility layer sets it to 1 as a way for mods to identify if they are running pure SMAPI or FarmHand compatibility.

**Comment by BlueRaja** [comment]
@Entoarox That is not an acceptable thing for them to do.

**Comment by Entoarox** [comment]
@BlueRaja Since CLxS is the one who did so, and he is the one who chose for SMAPI to be maintenance-only from now on, it is quite acceptable.

**Comment by Pathoschild** [comment]
Hi @Entoarox. Farmhand sets the version to "1.0.0 Farmhand-Smapi". If a mod needs to know whether it's using the compatibility layer, it should check for the "Farmhand-Smapi" tag rather than the number. Depending on the number itself is bad practice.

 Although the plan is to transition to Farmhand when that's released, SMAPI is not currently maintenance-only. The development goal is to clean up SMAPI and fix known issues, make it crossplatform, and smooth out the eventual transition to Farmhand (e.g. #156).
