### ISSUE TITLE
Add spawning of tools to trainer

### ISSUE THREAD

**Issue by ClxS** [ClxS/SMAPI#11]

**Comment by vgturtle127** [comment]
@ClxS Spawning of items in general would be nice.

**Comment by speeder** [comment]
vgturtle the traitor already has general item spawning, it is that tools and machines need special coding.

**Comment by vgturtle127** [comment]
@speeder You mean the trainer supports spawning the item, but the item has no functionality when spawned?

**Comment by speeder** [comment]
Not even that... I was modding the kegs for example, and didn't found any obvious way to spawn one beside editing my save to give myself the crafting recipe, and then giving myself the materials.

Even by peeking into the game source, I didn't found out how, because it works in a completely different manner.

tools, same thing.

**Comment by vgturtle127** [comment]
@speeder Dang, that sounds fairly complex. I suppose the game did just come out, so it may be that it is pretty early.

**Comment by CJBok** [comment]
I'll mark this one as closed as the trainer mod is a good example mod. Other mods are doing a better job anyways :)
