### ISSUE TITLE
Weird green lines and resolution issues

### ISSUE THREAD

**Issue by Elenocora** [ClxS/SMAPI#145]
Every time I open up Stardew Valley via the Modding API the screen is either completely or in part framed by a green line ... Sometimes it's a smaller window where there is also a white line visible "from underneath"

The lines stop once I open up a save, but then other issues take over ... Like the resolution changing, though I set it to a certain number and full screen the "day before" in-game and also irl ...
(This isn't the case when I don't start via API)

Sometimes re-changing the resolution also affects the size of other windows and fonts on my desktop ...

Please help me ... I don't know what to do

PS: It would be REALLY helpful if there was a notification once a new version of SMAPI was available ...
Manually checking every day or two is such a chore >.<

**Comment by Pathoschild** [comment]
Hi @Elenocora. Does this still happen with the latest version of Stardew Valley and SMAPI? If so, please reply with a screenshot and your latest log file (see [this guide](http://canimod.com/guides/asking-for-help#information-to-include)). If not, reply so we can close the ticket. :)

**Comment by Pathoschild** [comment]
Closed due to inactivity. If this still happens with the latest version of Stardew Valley and SMAPI, come ask for help in the [Stardew Valley Discord](https://discord.gg/KCJHWhX) or the [discussion thead on the official forums](http://community.playstarbound.com/threads/stardew-modding-api-0-40-1-1.108375/) and we'll help you figure it out. :)
