### ISSUE TITLE
SkillPrestige Mod - Crash on game exit.

### ISSUE THREAD

**Issue by Iomega0318** [ClxS/SMAPI#162]
So I posted this over on their github well over a week ago and have had no response.

Reading it a bit further and as I have no idea whether it is the Prestige Mod itself or the API I figured I would post it here as well just in case.

Please let me know if you need any more info.
(Also let me know if it's their mod or the API since I haven't a clue!)

Thank you.

https://github.com/Alphablackwolf/SkillPrestige/issues/2

**Comment by Pathoschild** [comment]
Hi @Iomega0318. This looks like an issue with the skill prestige mod. It has some logic to load sub-mods, which is apparently crashing on exit. If you've added any sub-mods, you can try removing those; otherwise you'll need to wait for the author to look into it. The author committed a change to the repository two days ago, so they're not inactive.

**Comment by Iomega0318** [comment]
Awesome thank you for the quick reply, I just needed to know where to pursue the fix!

Also yeah I posted it it almost 2 weeks ago, when I added the mod I actually didn't add any of his sub mods in I just wanted to prestige my skills, I have since added in the Luck and Cooking skills and it's the exact same error.

Again thank you for the reply :)
