### ISSUE TITLE
Can't load SMAPI when updated

### ISSUE THREAD

**Issue by unclepopeye** [ClxS/SMAPI#167]
Hi I just cant load the game anymore trough StardewModdingAPI though it run just fine if I started it trough the normal stardew valley.exe
The log always shows some red letters telling me that it failed to load. I attached the error log from the Appdata in this post
[MODDED_ProgramLog.Log_LATEST.txt](https://github.com/ClxS/SMAPI/files/584947/MODDED_ProgramLog.Log_LATEST.txt)

**Comment by unclepopeye** [comment]
Btw it still the same when I still used the 1.1 updated version, though it seemed that there were a red line in he middle which told me to update into the 1.11 version, but in the end they both still wont allow me to launch a modded game.

**Comment by Pathoschild** [comment]
Hi @unclepopeye. Your error is caused by the [Reusable Wallpapers and Floors](http://www.nexusmods.com/stardewvalley/mods/356/) mod, which isn't compatible with the latest version of Stardew Valley. You'll need to remove that mod to continue playing. Fortunately the [new catalogue item](http://stardewvalleywiki.com/Catalogue) mostly replaces it.
