### ISSUE TITLE
Skills sometimes revert back or change randomly

### ISSUE THREAD

**Issue by vgturtle127** [ClxS/SMAPI#26]
Sometimes skills will change back to lower levels, even if I set my level to 10.

**Comment by speeder** [comment]
Care to give more explanation of when this happen?
Mind you, setting your level is a buggy thing, you should not do it in general, first because it skips the game internal code that give you recipes, bonuses and whatnot.
Also, because the game also tracks when you levelled up, and might decide to undo your "corrupted" skill level.

**Comment by vgturtle127** [comment]
@speeder Well, it usually happens after I use the skill for a while. You are correct about it being buggy, because sometimes I can use a skill for a very long time and nothing will change, but other times right after I use it the next time it reverts back to level 1.

**Comment by vgturtle127** [comment]
@speeder I wish you could set your level back to 1, but you can't even do that without bugs. :cry:

**Comment by speeder** [comment]
If you meddled with your level in a save file without backup... it can't be fixed, sorry...

I use level editing exclusively to test stuff, the games DOES NOT tolerate level changing, the level code is extremely confusing, spread out over several places in the source (instead of being the sane thing of everything being handled on the same place).

The best maybe a mod can do, is simulate you getting XP, and invoking a certain function of the game several times in a row, then allowing you to level up a night, still, that only works to increase your level (instead of decrease), you can't get to max level in one day (the game doesn't allow it), and doesn't work for the hidden "luck" skill.

**Comment by vgturtle127** [comment]
@speeder I think I will try to make a mod that just gives you XP. That may be a good place to start.
